name: Run tests and build docs


on:
  push:
    branches: [ main, le_nao_feb2026 ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt
        pip install .
        # --- Ensure correct Starsim/STIsim versions (override cache) ---
        pip install --force-reinstall starsim==3.0.3 STIsim==1.4.0

    - name: Run tests
      env:
        NUMBA_CACHE_DIR: ${{ github.workspace }}/.numba_cache
        NUMBA_CACHE_LOCATOR_CLASSES: UserWideCacheLocator,IPythonCacheLocator
      run: |
        mkdir -p "$NUMBA_CACHE_DIR"
        pytest tests/

    - name: Build documentation
      run: |
        sphinx-build -b html docs docs/_build/html
        
