name: Run tests and build docs


on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt
        pip install .

    - name: Run tests
      run: |
        pytest tests/

    - name: Build documentation
      run: |
        sphinx-build -b html docs docs/_build/html
